# Generated by Django 4.2.2 on 2023-07-01 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telehealth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('symptoms', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation',
            field=models.OneToOneField(default=22, on_delete=django.db.models.deletion.CASCADE, to='telehealth_app.consultation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='consultation_type',
            field=models.CharField(choices=[('initial', 'Initial Consultation'), ('follow_up', 'Follow-up')], max_length=20),
        ),
    ]
